module.exports = {
  cloud: [
    /*
    {
      type: 'autogenerated',
      dirName: '.',
    },
    */
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {
          type: 'doc',
          id: 'getting_started',
        },
        {
          "type": "category",
          "label": "Support",
          "items": [
            {
              "type": "doc",
              "id": "support/contact_us"
            },
          ],
        },
      ],
    },
  ],
};